In [7]:
def division(x,y):
    try:
        result=x/y
        print('ans is:',result)
    except ZeroDivisionError :
          print('Division by zero is npt allowed')
division(10,2) 
division(10,0)

ans is: 5.0
Division by zero is npt allowed


In [11]:
subject = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball","cricket"]
for i in subject:
    for j in verb:
        for s in obj:
            print(i+" "+j+" "+s+".")

Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


In [17]:
import numpy as np
x=np.array([1,2,3,4,5])
N=4
matrix1=np.vander(x,N)
print(matrix1)




[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
